spring.application.name=demo
# 1. ??a ch? k?t n?i ??n MySQL (cinehub_db là tên database b?n t?o lúc nãy)
spring.datasource.url=jdbc:mysql://localhost:3306/cinehub_db?useSSL=false&serverTimezone=UTC

# 2. Tài kho?n và m?t kh?u MySQL c?a b?n
spring.datasource.username=root
spring.datasource.password=anhyeuem123

# 3. Driver ?? Java nói chuy?n v?i MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. C?u hình Hibernate (nh? mình ?ã nói ? b??c tr??c)
# Chuy?n thành 'none' vì b?n ?ã ch?y file SQL th? công r?i
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true